```yaml
#theme: jekyll-theme-minimal
#title: ğŸ’»âœ’ï¸ğŸ“„ğŸŒŸ
description: Abe's CV
title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
```
